spring:
  application:
    name: "offer-technical-test"
    description: @project.description@
    version: @project.version@
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false
  jackson:
    time-zone: Europe/Paris
    locale: FR

server:
  servlet:
    context-path: /offer-api

